version: "3"
services:
  back:
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=./
  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
