version: "3"
services:
  back:
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PYTHONPATH=./
  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "443:8080"
  head:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
        